#' Correction of OCR Issues
#'
#' Regular expression based correction of scanning issues.
#' @param x character vector to be corrected
#' @return character vector
#' @export
correct_ocr <- function(x){
  x <- gsub("gafse","gasse",x)
  x <- gsub("NachtLock","Nachtrock",x)
  x <- gsub("Offlzier","Offizier",x)
  x <- gsub("Unis(ö|o)rm","Uniform",x)
  x <- gsub("znisorm","Uniform",x)
  x <- gsub("Unfform","Uniform",x)
  x <- gsub("Umform","Uniform",x)
  x <- gsub("Unifarm","Uniform",x)
  x <- gsub("Untform","Uniform",x)
  x <- gsub("Aniform","Uniform",x)
  x <- gsub("Unia\\sform","Uniform",x)
  x <- gsub("Uni\\sform","Uniform",x)
  x <- gsub("Unifokm","Uniform",x)
  x <- gsub("Uniforin","Uniform",x)
  x <- gsub("sischbein","fischbein",x)
  x <- gsub("Wähstuhl","Wäbstuhl",x)
  x <- gsub("Strumpfwber","Strumpfweber",x)
  x <- gsub("Corseis","Corsets",x)
  x <- gsub("Peiz","Pelz",x)
  x <- gsub("erfrazen","erfragen",x)
  x <- gsub("Abbrücke","Abdrücke",x)
  x <- gsub("Fastor","Pastor",x)
  x <- gsub("Ptstorius","Pistorius",x)
  x <- gsub("Schweiahaus","Schweighaus",x)
  x <- gsub("Burtorf","Buxtorf",x)
  x <- gsub("Lortorie","Lotterie",x)
  x <- gsub("Buchbruck","Buchdruck",x)
  x <- gsub("Brhausung","Behausung",x)
  x <- gsub("Adstattung","Erstattung",x)
  x <- gsub("Rnetor","Rhetor",x)
  x <- gsub("allhter","allhier",x)
  x <- gsub("Churneysen","Thurneysen",x)
  x <- gsub("Churneysens","Thurneysens",x)
  x <- gsub("ehristliche","christliche",x)
  x <- gsub("Lottorie","Lotterie",x)
  x <- gsub("nIntoresse","Interesse",x)
  x <- gsub("Intoressent","Interessent",x)
  x <- gsub("Intoressenten","Interessenten",x)
  x <- gsub("Intoresse","Interesse",x)
  x <- gsub("Missenschafften","Wissenschafften",x)
  x <- gsub("Pissenschafften","Wissenschafften",x)
  x <- gsub("Mgaß","Maas",x)
  x <- gsub("Mgas","Maas",x)
  x <- gsub("Bläfinthor","Bläsinthor",x)
  x <- gsub("Erpeditor","Expeditor",x)
  x <- gsub("Eypeditor","Expeditor",x)
  x <- gsub("Hanbelshaus","Handelshaus",x)
  x <- gsub("Rhengas","Rheingas",x)
  x <- gsub("Leonbardskirch","Leonhardskirch",x)
  x <- gsub("Resivenzstadt","Residenzstadt",x)
  x <- gsub("Aéschenvorstadt","Aeschenvorstadt",x)
  x <- gsub("Pnstor","Pastor",x)
  x <- gsub("Drichthaus","Berichthaus",x)
  x <- gsub("Adeiberg","Adelberg",x)
  x <- gsub("Creoitor","Creditor",x)
  x <- gsub("Greisfengaß","Greiffengaß",x)
  x <- gsub("Baurfüßerplatz","Baarfüßerplatz",x)
  x <- gsub("Schützonhaus","Schützenhaus",x)
  x <- gsub("Aoschenvorstadt","Aeschenvorstadt",x)
  x <- gsub("Kutielgäß","Kuttelgäß",x)
  x <- gsub("Oönabruck","Osnabruck",x)
  x <- gsub("Kheinbrück","Rheinbrück",x)
  x <- gsub("Leonhaodsberg","Leonhardsberg",x)
  x <- gsub("Martinstirchhof","Martinskirchhof",x)
  x <- gsub("Handlüngshaus","Handlungshaus",x)
  x <- gsub("Marigkirch","Mariakirch",x)
  x <- gsub("Koramarkt","Kornmarkt",x)
  x <- gsub("Séhrotberg","Schrotberg",x)
  x <- gsub("Jshannthor","Johannthor",x)
  x <- gsub("Aescherporstadt","Aeschenvorstadt",x)
  x <- gsub("Berichshaus","Berichthaus",x)
  x <- gsub("Kiybeckstras","Klybeckstras",x)
  x <- gsub("Aeschekthor","Aeschenthor",x)
  x <- gsub("Aescherverstadt","Aeschenvorstadt",x)
  x <- gsub("Diredtor","Director",x)
  x <- gsub("Piarrhaus","Pfarrhaus",x)
  x <- gsub("Louisdtor","Louis d'Or",x)
  x <- gsub("Beriehthaus","Berichthaus",x)
  x <- gsub("Berachthaus","Berichthaus",x)
  x <- gsub("Berlchthaus","Berichthaus",x)
  x <- gsub("Prceptor","Präceptor",x)
  x <- gsub("IJmhof","Imhof",x)
  x <- gsub("Wirthsöhaus","Wirthshaus",x)
  x <- gsub("Karnmarckt","Kornmarckt",x)
  x <- gsub("Leonhardslkirch","Leonhardskirch",x)
  x <- gsub("Stenenberg","Sternenberg",x)
  x <- gsub("Zerichthaus","Berichthaus",x)
  x <- gsub("MWürkenberg","Würtenberg",x)
  x <- gsub("Soriptor","Scriptor",x)
  x <- gsub("BVerichthaus","Berichthaus",x)
  x <- gsub("Greiffsengaß","Greiffengaß",x)
  x <- gsub("Greisengaß","Greifengaß",x)
  x <- gsub("Berichehaus","Berichthaus",x)
  x <- gsub("Barichthaus","Berichthaus",x)
  x <- gsub("Frschgaß","Fröschgaß",x)
  x <- gsub("Pelerskirch","Peterskirch",x)
  x <- gsub("Prcrceptor","Preceptor",x)
  x <- gsub("Wirthähaus","Wirthshaus",x)
  x <- gsub("Wrtemberg","Würtemberg",x)
  x <- gsub("Verichthaus","Berichthaus",x)
  x <- gsub("Jerichthaus","Berichthaus",x)
  x <- gsub("Fronfgstenmarkt","Fronfastenmarkt",x)
  x <- gsub("Juformator","Informator",x)
  x <- gsub("Vostadt","Vorstadt",x)
  x <- gsub("Bläispthor","Bläisythor",x)
  x <- gsub("RRebgaß","Rebgaß",x)
  x <- gsub("Werekstatt","Werckstatt",x)
  x <- gsub("Teillengäß","Trillengäß",x)
  x <- gsub("Pfaerhaus","Pfarrhaus",x)
  x <- gsub("Berichhaus","Berichthaus",x)
  x <- gsub("Drector","Director",x)
  x <- gsub("Berichihaus","Berichthaus",x)
  x <- gsub("Ferichthaus","Berichthaus",x)
  x <- gsub("Peteroplatz","Petersplatz",x)
  x <- gsub("Imvergäß","Imbergäß",x)
  x <- gsub("Freyonstraß","Freyenstraß",x)
  x <- gsub("Bertchthaus","Berichthaus",x)
  x <- gsub("Beuichthaus","Berichthaus",x)
  x <- gsub("Berichrhaus","Berichthaus",x)
  x <- gsub("Borstatt","Vorstatt",x)
  x <- gsub("Bevichthaus","Berichthaus",x)
  x <- gsub("Gerbeagaß","Gerbergaß",x)
  x <- gsub("Korumarkt","Kornmarkt",x)
  x <- gsub("Birichthaus","Berichthaus",x)
  x <- gsub("Paisenhaus","Waisenhaus",x)
  x <- gsub("Berchthaus","Berichthaus",x)
  x <- gsub("Berschthaus","Berichthaus",x)
  x <- gsub("Rhemsprung","Rheinsprung",x)
  x <- gsub("Daisenhaus","Waisenhaus",x)
  x <- gsub("Nünsterplatz","Münsterplatz",x)
  x <- gsub("Herichthaus","Berichthaus",x)
  x <- gsub("Zerichthaus","Berichthaus",x)
  x <- gsub("Schneibergas","Schneidergas",x)
  x <- gsub("Gothof","Guthof",x)
  x <- gsub("berschiedene","verschiedene",x)
  x <- gsub("Kopnmarckt","Kornmarckt",x)
  x <- gsub("Berichlhaus","Berichthaus",x)
  x <- gsub("Matkinsgaß","Martinsgaß",x)
  x <- gsub("Korumarckt","Kornmarckt",x)
  x <- gsub("Herüberg","Heüberg",x)
  x <- gsub("Spittablsprung","Spittahlsprung",x)
  x <- gsub("Köngsberg","Königsberg",x)
  x <- gsub("Nenstatt","Neustatt",x)
  x <- gsub("Beunngäß","Brunngäß",x)
  x <- gsub("Praaeptor","Praeceptor",x)
  x <- gsub("Compofitor","Compositor",x)
  x <- gsub("Riudermarckt","Rindermarckt",x)
  x <- gsub("Rludermarckt","Rindermarckt",x)
  x <- gsub("Klrchhof","Kirchhof",x)
  x <- gsub("KHutgaß","Hutgaß",x)
  x <- gsub("Verstadt","Vorstadt",x)
  x <- gsub("Vodstadt","Vorstadt",x)
  x <- gsub("Epahlenberg","Spahlenberg",x)
  x <- gsub("Streilgaß","Streitgaß",x)
  x <- gsub("Rhrinsprung","Rheinsprung",x)
  x <- gsub("Scklüsselberg","Schlüsselberg",x)
  x <- gsub("Kllchgäß","Kilchgäß",x)
  x <- gsub("Pfarthof","Pfarrhof",x)
  x <- gsub("Hntgaß","Hutgaß",x)
  x <- gsub("Gerwergaß","Gerbergaß",x)
  x <- gsub("Frofastenmarckt","Fronfastenmarckt",x)
  x <- gsub("Gerwergäß","Gerbergäß",x)
  x <- gsub("Todtentan;","Todtentanz",x)
  x <- gsub("Ehsengaß","Eisengaß",x)
  x <- gsub("Jorstatt","Vorstatt",x)
  x <- gsub("Pfarchof","Pfarrhof",x)
  x <- gsub("Pfarihof","Pfarrhof",x)
  x <- gsub("Pfarahof","Pfarrhof",x)
  x <- gsub("Rheilgaß","Rheingaß",x)
  x <- gsub("CAdelberg","Adelberg",x)
  x <- gsub("Albanvopstadt","Albanvorstadt",x)
  x <- gsub("Froufastenmarkt","Fronfastenmarkt",x)
  x <- gsub("Geeberberg","Gerberberg",x)
  x <- gsub("Gemöberg","Gemsberg",x)
  x <- gsub("Lpahlenberg","Spahlenberg",x)
  x <- gsub("Aescheyvorstadt","Aeschenvorstadt",x)
  x <- gsub("Arschenvorstadt","Aeschenvorstadt",x)
  x <- gsub("Pfingstfroufastenmarkt","Pfingstfronfastenmarkt",x)
  x <- gsub("Johannorstadt","Johannvorstadt",x)
  x <- gsub("Berlchthaus","Berichthaus",x)
  x <- gsub("Albanporstadt","Albanvorstadt",x)
  x <- gsub("Rhelngaß","Rheingaß",x)
  x <- gsub("Fohannvorstadt","Johannvorstadt",x)
  x <- gsub("Vor8stadt","Vorstadt",x)
  x <- gsub("Bnarfusserplatz","Barfusserplatz",x)
  x <- gsub("Berschthaus","Berichthaus",x)
  x <- gsub("Berickthaus","Berichthaus",x)
  x <- gsub("Pfarthof","Pfarrhof",x)
  x <- gsub("Brchthaus","Berichthaus",x)
  x <- gsub("Spahleuberg","Spalenberg",x)
  x <- gsub("Eifengas","Eisengas",x)
  x <- gsub("Berschthaus","Berichthaus",x)
  x <- gsub("Rerichthaus","Berichthaus",x)
  x <- gsub("Affortment","Assortiment",x)
  x <- gsub("Geismlilch","Geismilch",x)
  x <- gsub("Spanserckel","Spanferckel",x)
  x <- gsub("Kirfzwasser","Kirschwasser",x)
  x <- gsub("Bnchbender","Buchbender",x)
  x <- gsub("Stocksich","Stockfisch",x)
  x <- gsub("Margräferwen","Margräferwein",x)
  x <- gsub("Geschirt","Geschirr",x)
  x <- gsub("Rußwasser","Nußwasser",x)
  x <- gsub("Eigarren","Cigarren",x)
  x <- gsub("Fakob","Jakob",x)
  x <- gsub("Jakoh","Jakob",x)
  x <- gsub("nndeln","nudeln",x)
  x <- gsub("Moufarde","Moustarde",x)
  x <- gsub("Saurtraut","Saurkraut",x)
  x <- gsub("Chnocolade","Chocolade",x)
  x <- gsub("Geismlilch","Geismilch",x)
  x <- gsub("Mollisisch","Mollifisch",x)
  x <- gsub("Stocksisch","Stockfisch",x)
  x <- gsub("Meextrauben","Meertrauben",x)
  x <- gsub("Feler-spritzen","Feuer-spritzen",x)
  x <- gsub("Korn\\smesser","Kornmesser",x)
  x <- gsub("Schnei\\sder","Schneider",x)
  x <- gsub("Vei\\b","Bei\\b",x)
  x <- gsub("Melster","Meister",x)
  x <- gsub("Monhieur","Monsieur",x)
  x <- gsub("Lndenmeyers","Lindenmeyers",x)
  x <- gsub("Zerr","Herr",x)
  x <- gsub("Ifelin","Iselin",x)
  x <- gsub("Hermn","Herrn",x)
  x <- gsub("fungfer","Jungfer",x)
  x <- gsub("be\\sstens","bestens",x)
  x <- gsub("Bhilosophische","Philosophische",x)
  x <- gsub("latemisch","lateinisch",x)
  x <- gsub("latemnisches","lateinisches",x)
  x <- gsub("Weiberßtz","Weibersitz",x)
  x <- gsub("Josepl","Joseph",x)
  x <- gsub("fungfer","Jungfer",x)
  x <- gsub("Emauuel","Emanuel",x)
  x <- gsub("Ikaliänisch","Italiänisch",x)
  x <- gsub("leder gehunden","leder gebunden",x)
  x <- gsub("Leder gehunden","Leder gebunden",x)
  x <- gsub("Frmu\\b","Frau\\b",x)
  x <- gsub("Fral\\b","Frau\\b",x)
  x <- gsub("Hern","Herrn",x)
  x <- gsub("Franu\\b","Frau\\b",x)
  x <- gsub("Fran\\b","Frau\\b",x)
  x <- gsub("ekwas","etwas",x)
  x <- gsub("Axx sols","xxx sols",x)
  x <- gsub("RRx sols","xxx sols",x)
  x <- gsub("Rxx sols","xxx sols",x)
  x <- gsub("RxKsols","xxx sols",x)
  x <- gsub("Miinsteri","Münsteri",x)
  x <- gsub("Ikaliänisch","Italiänisch",x)
  x <- gsub("Artzneh-Buch","Artzney-Buch",x)
  x <- gsub("4trlas","Attlas",x)
  x <- gsub("Atrlas","Attlas",x)
  x <- gsub("Artlas","Attlas",x)
  x <- gsub("Milck-Kuhe","Milch-Kuhe",x)
  x <- gsub("Tert\\b","Text\\b",x)
  x <- gsub("Gualiter","Qualitet",x)
  x <- gsub("Erlguterung","Erläuterung",x)
  x <- gsub("Staliänischer","Italiänischer",x)
  x <- gsub("Dictionanium","Dictionarium",x)
  x <- gsub("3tem\\b","Item\\b",x)
  x <- gsub("Cafsa","Cassa",x)
  x <- gsub("Adresse-Contot","Adresse-Contor",x)
  x <- gsub("Testamenri","Testamenti",x)
  x <- gsub("darmnen","darinnen",x)
  x <- gsub("Frannösischen","Französischen",x)
  x <- gsub("Latemischen"," Lateinischen",x)
  x <- gsub("Endiaung","Endigung",x)
  x <- gsub("Hermn","Herrn",x)
  x <- gsub("Herin","Herrn",x)
  x <- gsub("Chee\\b","Chez\\b",x)
  x <- gsub("Blnmen","Blumen",x)
  x <- gsub("Zerr\\b","Herr\\b",x)
  x <- gsub("Madlame","Madame",x)
  x <- gsub("Mfr\\.","Mstr\\.",x)
  x <- gsub("Relariones","Relationes",x)
  x <- gsub("Relariones","Relationes",x)
  x <- gsub("Architestur","Architectur",x)
  x <- gsub("lnsormation","Information",x)
  x <- gsub("Rechenkunt","Rechenkunst",x)
  x <- gsub("dielenigen","diejenigen",x)
  x <- gsub("Drucktischan","Drucktischen",x)
  x <- gsub("Bonteille","Bouteille",x)
  x <- gsub("Hril","Heil",x)
  x <- gsub("Schuit","Schutt",x)
  x <- gsub("Gelosäck","Geldsäck",x)
  x <- gsub("Uis","bis",x)
  x <- gsub("Orvonnanz","Ordonnanz",x)
  x <- gsub("GedanLen","Gedanken",x)
  x <- gsub("Magnetlsmus","Magnetismus",x)
  x <- gsub("Ehaise","Chaise",x)
  x <- gsub("Pfalmbuch","Psalmbuch",x)
  x <- gsub("Büchbinder","Buchbinder",x)
  x <- gsub("Johl Jal\\. Flick","Joh\\. Jak\\. Flick",x)
  x <- gsub("J\\. Jal\\. Flick","J\\. Jak\\. Flick",x)
  x <- gsub("Plalm-Buch","Psalm-Buch",x)
  x <- gsub("Psaln buch","Psalm-Buch",x)
  x <- gsub("\\& alm-Buch","Psalm-Buch",x)
  x <- gsub("Psatmenbuch","Psalmenbuch",x)
  x <- gsub("Pfalmenbuch","Psalmenbuch",x)
  x <- gsub("Rorrerdam","Rotterdam",x)
  x <- gsub("gutspnrechen","gutsprechen",x)
  x <- gsub("Freyeompagnie","Freycompagnie",x)
  x <- gsub("9oo","900",x)
  x <- gsub("Antiquiteren","Antiquiteten",x)
  x <- gsub("Anriquiteten","Antiquiteten",x)
  x <- gsub("ertra","extra",x)
  x <- gsub("Miinsters","Münsters",x)
  x <- gsub("Hobelbant","Hobelbank",x)
  x <- gsub("Kirschwaffer","Kirschwasser",x)
  x <- gsub("Mitteltos","Mittellos",x)
  x <- gsub("mitteltos","mittellos",x)
  x <- gsub("Blbli","Biblio",x)
  x <- gsub("Grld","Geld",x)
  x <- gsub("stemern","steinern",x)
  x <- gsub("Ausleihem","Ausleihen",x)
  x <- gsub("zu rauffen","zu kauffen",x)
  x <- gsub("Verfauf","Verkauf",x)
  x <- gsub("zurauffen","zu kauffen",x)
  x <- gsub("zukaufsen","zu kauffen",x)
  x <- gsub("Insormation","Information",x)
  x <- gsub("Zingegen","Hingegen",x)
  x <- gsub("Veustorben","Verstorben",x)
  x <- gsub("VBerlorne","Verlorne",x)
  x <- gsub("Bedlenung","Bedienung",x)
  x <- gsub("\\btost","Kost",x)
  x <- gsub("Informakion","Information",x)
  x <- gsub("Bebienung","Bedienung",x)
  x <- gsub("Perstorben","Verstorben",x)
  x <- gsub("Per st or ben","Verstorben",x)
  x <- gsub("Informagtion","Information",x)
  x <- gsub("Merkwürdigkelt","Merkwürdigkeit",x)
  x <- gsub("Merckmürdigkeit","Merkwürdigkeit",x)
  x <- gsub("Merkwüirdigkett","Merkwürdigkeit",x)
  x <- gsub("Merkwüirdigkelt","Merkwürdigkeit",x)
  x <- gsub("Merkwüirdigkeit","Merkwürdigkeit",x)
  x <- gsub("Merkwirdlgklelt","Merkwürdigkeit",x)
  x <- gsub("Lerlorne","Verlorne",x)
  x <- gsub("Ktost","Kost",x)
  x <- gsub("Inormation","Information",x)
  x <- gsub("Juformation","Information",x)
  x <- gsub("Jnsormgtion","Information",x)
  x <- gsub("Jnsormatkion","Information",x)
  x <- gsub("Iuformation","Information",x)
  x <- gsub("Informgtion","Information",x)
  x <- gsub("Insormation","Information",x)
  x <- gsub("Informaton","Information",x)
  x <- gsub("Informatien","Information",x)
  x <- gsub("Infonmation","Information",x)
  x <- gsub("Bedienun gen","Bedienungen",x)
  x <- gsub("Jnformation","Information",x)
  x <- gsub("Informatton","Information",x)
  x <- gsub("Bediemngen","Bedienung",x)
  x <- gsub("Imsormation","Information",x)
  x <- gsub("Buchhandlun\\b","Buchhandlung",x)
  x <- gsub("Buchhandlnng","Buchhandlung",x)
  x <- gsub("Büchhandlung","Buchhandlung",x)
  x <- gsub("Buchhandilung","Buchhandlung",x)
  x <- gsub("Buchhaudlung","Buchhandlung",x)
  x <- gsub("Buchhäudler","Buchhändler",x)
  x <- gsub("Buchhändier","Buchhändler",x)
  x <- gsub("Buchbändler","Buchhändler",x)
  x <- gsub("Buchbin\\. der","Buchbinder",x)
  x <- gsub("Bnchhandlung","Buchhandlung",x)
  x <- gsub("Heineich Haag","Heinrich Haag",x)
  x <- gsub("Joh\\. Jgkob Freyler","Joh\\. Jakob Freyler",x)
  x <- gsub("Buchenhol3","Buchenholz",x)
  x <- gsub("Lerikon","Lexikon",x)
  x <- gsub("E\\. A\\. Serint","C\\. A\\. Serini",x)
  x <- gsub("E\\. A\\. Serini","C\\. A\\. Serini",x)
  x <- gsub("C\\. A\\. Serint","C\\. A\\. Serini",x)
  x <- gsub("Buchhändlet","Buchhändler",x)
  x <- gsub("Merlanischen Kupfern","Merianischen Kupfern",x)
  x <- gsub("Merlanische Kupfer","Merianische Kupfer",x)
  x <- gsub("Buchb inder","Buchbinder",x)
  x <- gsub("Buch\\. binder","Buchbinder",x)
  x <- gsub("Joh\\. Jak\\. Frehler","Joh\\. Jak\\. Freyler",x)
  x <- gsub("Conror","Contor",x)
  x <- gsub("zu rauffenbe","zu rauffen be",x)
  x <- gsub("entkehnen","entlehnen",x)
  x <- gsub("Pegehrt","begehrt",x)
  x <- gsub("entkehnen","entlehnen",x)
  x <- gsub("ftoft","Kost",x)
  x <- gsub("fost","Kost",x)
  x <- gsub("foft","Kost",x)
  x <- gsub("KKost","Kost",x)
  x <- gsub("Koft","Kost",x)
  x <- gsub("Informgtkion","Information",x)
  x <- gsub("Informatkion","Information",x)
  x <- gsub("Insormation","Information",x)
  x <- gsub("Fingegen","Hingegen",x)
  x <- gsub("zugentlehnen","zu entlehnen",x)
  x <- gsub("angetr agen","angetragen",x)
  x <- gsub("angeragen","angetragen",x)
  x <- gsub("angekragen","angetragen",x)
  x <- gsub("Verkäuf","Verkauf",x)
  x <- gsub("Perkauf","Verkauf",x)
  x <- gsub("zum erkauf","zum Verkauf",x)
  x <- gsub("Derkauf","Verkauf",x)
  x <- gsub("Berkauf","Verkauf",x)
  x <- gsub("Austeiben","Ausleihen",x)
  x <- gsub("offerierti","offeriert",x)
  x <- gsub("öfferiert","offeriert",x)
  x <- gsub("offerierk","offeriert",x)
  x <- gsub("Ausleiten","Ausleihen",x)
  x <- gsub("Ausieihen","Ausleihen",x)
  x <- gsub("Ansleihen","Ausleihen",x)
  x <- gsub("Derstorbe","Verstorbe",x)
  x <- gsub("Derlorne","Verlorne",x)
  x <- gsub("Der storbe","Verstorbe",x)
  x <- gsub("Der stor be","Verstorbe",x)
  x <- gsub("Der st or be","Verstorbe",x)
  x <- gsub("ynformation","Information",x)
  x <- gsub("Berlorne","Verlorne",x)
  x <- gsub("Belegenheit","Gelegenheit",x)
  x <- gsub("Landschast","Landschaft",x)
  x <- gsub("ehelch","ehelich",x)
  x <- gsub("chelich","ehelich",x)
  x <- gsub("eelich","ehelich",x)
  x <- gsub("Armie und","Arme und",x)
  x <- gsub("Branke","Kranke",x)
  x <- gsub("Nachrihten","Nachrichten",x)
  x <- gsub("Allerhand achrichten","Allerhand Nachrichten",x)
  x <- gsub("Allerhänd","Allerhand",x)
  x <- gsub("Alerhand","Allerhand",x)
  x <- gsub("Rachrichten","Nachrichten",x)
  x <- gsub("Aerhand","Allerhand",x)
  x <- gsub("zuberläßig","zuverläßig",x)
  x <- gsub("Rechenhunst","Rechenkunst",x)
  x <- gsub("Jonesessel","Joncsessel",x)
  x <- gsub("Revetir","Repetir",x)
  x <- gsub("zweysitziees","zweysitziges",x)
  x <- gsub("Mabratze","Madratze",x)
  x <- gsub("Fortepians","Fortepiano",x)
  x <- gsub("Elnabeth","Elisabeth",x)
  x <- gsub("Finder-Bett","Kinder-Bett",x)
  x <- gsub("Gefindobett","Gesindsbett",x)
  x <- gsub("minder Vasel","minder Basel",x)
  x <- gsub("Jone-Sessel","Jonc-Sessel",x)
  x <- gsub("Serdier","Servier",x)
  x <- gsub("kosmopsltische","kosmopolitische",x)
  x <- gsub("vatriotisch","patriotisch",x)
  x <- gsub("vraktisch","praktisch",x)
  x <- gsub("heldetische","helvetische",x)
  x <- gsub("belvetisch","helvetisch",x)
  x <- gsub("helbetisch","helvetisch",x)
  x <- gsub("Veiber","Weiber",x)
  x <- gsub("Tatack","Taback",x)
  x <- gsub("Tatack","Taback",x)
  x <- gsub("Kinchensitz","Kirchensitz",x)
  x <- gsub("Gestndsbett","Gesindsbett",x)
  x <- gsub("Drckbett","Deckbett",x)
  x <- gsub("Eltsabeth","Elisabeth",x)
  x <- gsub("Daonds-Harfe","Davids-Harfe",x)
  x <- gsub("Dapids-Harfe","Davids-Harfe",x)
  x <- gsub("Favence","Fayence",x)
  x <- gsub("Fayenee","Fayence",x)
  x <- gsub("Maiorica","Maiolica",x)
  x <- gsub("Ercellentz","Excellentz",x)
  x <- gsub("ercellent","excellent",x)
  x <- gsub("excellenr","excellent",x)
  x <- gsub("Klerder","Kleider",x)
  x <- gsub("Matraaen","Matratzen",x)
  x <- gsub("Strumypff","Strumpff",x)
  x <- gsub("albeiter","arbeiter",x)
  x <- gsub("floretsetdene","floretseidene",x)
  x <- gsub("sloretseide","floretseide",x)
  x <- gsub("Nglige","Neglige",x)
  x <- gsub("Frarzenzimmer","Frauenzimmer",x)
  x <- gsub("Hanshaltung","Haushaltung",x)
  x <- gsub("Gottschalt","Gottschalk",x)
  x <- gsub("Haushaltnng","Haushaltung",x)
  x <- gsub("Welberschuh","Weiberschuh",x)
  x <- gsub("Schuhschnadle","Schuhschnalle",x)
  x <- gsub("Lald-Mant","Laid-Mant",x)
  x <- gsub("Geldbentel","Geldbeutel",x)
  x <- gsub("Laldstrümpf","Laidstrümpf",x)
  x <- gsub("Franen-Strümpf","Frauen-Strümpf",x)
  x <- gsub("füchener","tüchener",x)
  x <- gsub("offtzier","offizier",x)
  x <- gsub("Mlode","Mode",x)
  x <- gsub("Rotenpapier","Notenpapier|Milchbrentl",x)
  x <- gsub("Gattersea","Battersea",x)
  x <- gsub("nutliche","nutzliche",x)
  x <- gsub("\\bBatter\\b","Gatter",x)
  x <- gsub("Strumpfwäber\\. Stuhl","Strumpfwäber-Stuhl",x)
  x <- gsub("Verkorne","Verlorne",x)
  x <- gsub("Stupanns","Stupanus",x)
  x <- gsub("I\\. Jakob Freyler","J\\. Jakob Freyler",x)
  x <- gsub("J\\. Jal\\. Freyler","J\\. Jak\\. Freyler",x)
  x <- gsub("Hemnrich Haag","Heinrich Haag",x)
  x <- gsub("Wilhelm Häas","Wilhelm Haas",x)
  x <- gsub("Wilheim Haas","Wilhelm Haas",x)
  x <- gsub("Johl Jal\\. Flick","Joh\\. Jak\\. Flick",x)
  x <- gsub("Bey Hry.","Bey Hrn.",x)
  x <- gsub("Jahnpulver","Zahnpulver",x)
  x <- gsub("Werckleug","Werckzeug",x)
  x <- gsub("unsehlbar","unfehlbar",x)
  x <- gsub("Parsumerie","Parfumerie",x)
  x <- gsub("Familie-Wasen","Familie-Wagen",x)
  x <- gsub("Frauenzimmer-Lebern","Frauenzimmer-Leibern",x)
  x <- gsub("käsicht","käficht",x)
  x <- gsub("Gutarre","Guitarre",x)
  x <- gsub("Steingnt","Steingut",x)
  x <- gsub("Nakulatur","Makulatur",x)
  x <- gsub("Zentner Ende","Zentner Erde",x)
  x <- gsub("\\bEnd\\b","Emd",x)
  x <- gsub("Eilsen","Eisen",x)
  x <- gsub("Einsat\\b","Einsatz",x)
  x <- gsub("Wachstertze","Wachskertze",x)
  x <- gsub("sichbein","fischbein",x)
  x <- gsub("Blaßhalb","Blaßbalg",x)
  x <- gsub("\\bBur\\b","Bux",x)
  x <- gsub("Tabartiere","Tabattiere",x)
  x <- gsub("Bauholt","Bauholz",x)
  x <- gsub("Leltfass","Leitfass",x)
  x <- gsub("Bauchosen","Bauchofen",x)
  x <- gsub("slehend","stehend",x)
  x <- gsub("Anwelsung","Anweisung",x)
  x <- gsub("Sternenmuhl","Sternenmehl",x)
  x <- gsub("Salffen","Saiffen",x)
  x <- gsub("Ramens","Namens",x)
  x <- gsub("Kesich","Kefich",x)
  x <- gsub("Elute","Flute",x)
  x <- gsub("Geitstock","Geldstock",x)
  x <- gsub("Elutes","Flutes",x)
  x <- gsub("Peister","Meister",x)
  x <- gsub("Urtzney","Artzney",x)
  x <- gsub("Wafften","Wafflen",x)
  x <- gsub("Marulatur","Makulatur",x)
  x <- gsub("Mannensauel","Mannensattel",x)
  x <- gsub("Weibersatte\\b","Weibersattel",x)
  x <- gsub("Wousseline","Mousseline",x)
  x <- gsub("Kutchen","Kutschen",x)
  x <- gsub("Eind\\b","Emd\\b",x)
  x <- gsub("Runst-Feuerwerk","Kunst-Feurwerk",x)
  x <- gsub("Fenereimer","Feuereimer",x)
  x <- gsub("NRußbaum","Nußbaum",x)
  x <- gsub("Dablien-Wurzeln","Dahlien-Wurzeln",x)
  x <- gsub("Blumenplaß","Blumenplatz",x)
  x <- gsub("Rußbaumholz","Nußbaumholz",x)
  x <- gsub("verkanffen","verkauffen",x)
  x <- gsub("Rüße","Nüße",x)
  x <- gsub("Rußbaum","Nußbaum",x)
  x <- gsub("Rußbäumern","Nußbäumern",x)
  x <- gsub("Ziertzig","Viertzig",x)
  x <- gsub("Gane-Bänd","Gaze-Bänd",x)
  x <- gsub("Kutchen-Kasten","Kutschen-Kasten",x)
  x <- gsub("Welbsbild","Weibsbild",x)
  x <- gsub("Brufstein","Brunstein",x)
  x <- gsub("Brun4","Brunn",x)
  x <- gsub("Buchlaven","Buchladen",x)
  x <- gsub("4tö","4tò",x)
  x <- gsub("4t0","4to",x)
  x <- gsub("4t6","4tò",x)
  x <- gsub("Schreib-Pull","Schreib-Pult",x)
  x <- gsub("keuchter","Leuchter",x)
  x <- gsub("Sratue","Statue",x)
  x <- gsub("Rähfaden","Nähfaden",x)
  x <- gsub("Groche","Broche",x)
  x <- gsub("Mirtur","Mixtur",x)
  x <- gsub("verohren","verloren",x)
  x <- gsub("Gare-Band","Gaze-Band",x)
  x <- gsub("verohren","verloren",x)
  x <- gsub("Gcosse","Grösse",x)
  x <- gsub("Lericon","Lexicon",x)
  x <- gsub("sleinerner","steinerner",x)
  x <- gsub("Cririca","Critica",x)
  x <- gsub("Ersindung","Erfindung",x)
  x <- gsub("Maugoldische","Mangoldische",x)
  x <- gsub("Käsich","Käfig",x)
  x <- gsub("Boureillen","Bouteillen",x)
  x <- gsub("Rinderspiel","Kinderspiel",x)
  x <- gsub("Bifouterie","Bijouterie",x)
  x <- gsub("Cafino","Casino",x)
  x <- gsub("Arrikel","Artikel",x)
  x <- gsub("Raffee","Kaffee",x)
  x <- gsub("kannerner","tannerner",x)
  x <- gsub("Museateller","Muscateller",x)
  x <- gsub("Musiepapier","Musicpapier",x)
  x <- gsub("lngenieur","Ingenieur",x)
  x <- gsub("Pelescop","Telescop",x)
  x <- gsub("AlckHosen","Alckhofen",x)
  x <- gsub("Nopembrit","Novembris",x)
  x <- gsub("Sistum","Bistum",x)
  x <- gsub("Weibersit","Weibersitz",x)
  x <- gsub("Welbersitz","Weibersitz",x)
  x <- gsub("Weidersitz","Weibersitz",x)
  x <- gsub("Eramine","Etamine",x)
  x <- gsub("besindlich","befindlich",x)
  x <- gsub("enedecke","entdecke",x)
  x <- gsub("Klydick","Klybeck",x)
  x <- gsub("Dictionaite","Dictionaire",x)
  x <- gsub("Persteigerung","Versteigerung",x)
  x <- gsub("oktapiges","oktaviges",x)
  x <- gsub("enidecke","entdecke",x)
  x <- gsub("8v0","8vo",x)
  x <- gsub("Haberfack","Habersack",x)
  x <- gsub("Rajonet","Bajonet",x)
  x <- gsub("Garnirure","Garniture",x)
  x <- gsub("Pretz","Preß",x)
  x <- gsub("Geuff","Genff",x)
  x <- gsub("Fabvik","Fabrik",x)
  x <- gsub("Wellbersack","Weibersack",x)
  x <- gsub("Hellbalsam","Heilbalsam",x)
  x <- gsub("Beselle","Geselle",x)
  x <- gsub("Veriug","Verzug",x)
  x <- gsub("FeloAnstalt","FeldAnstalt",x)
  x <- gsub("Rutzen","Nutzen",x)
  x <- gsub("Narschall","Marschall",x)
  x <- gsub("Chalse","Chaise",x)
  x <- gsub("vercalener","percalener",x)
  x <- gsub("besindlicher","befindlicher",x)
  x <- gsub("exrra","extra",x)
  x <- gsub("Zeuanuß","Zeugniß",x)
  x <- gsub("selner","seiner",x)
  x <- gsub("Zeuenuß","Zeugniß",x)
  x <- gsub("senaben","Knaben",x)
  x <- gsub("condirionirt","conditionirt",x)
  x <- gsub("Schuhladen","Schubladen",x)
  x <- gsub("Strumpffweder","Strumpffweber",x)
  x <- gsub("Setlinge","Setzlinge",x)
  x <- gsub("Strümpffweher","Strümpffweber",x)
  x <- gsub("weder-Stuhl","weber-Stuhl",x)
  x <- gsub("Weiver","Weiber",x, ignore.case = TRUE)
  x <- gsub("berzustellen","herzustellen",x)
  x <- gsub("anerblethet","anerbiethet",x)
  x <- gsub("alUirhand","allerhand",x)
  x <- gsub("Allerhans","Allerhand",x)
  x <- gsub("Srock","Stuck",x)
  x <- gsub("Eißbethen","Elisabethen",x)
  x <- gsub("AlickHosen","Alckofen",x)
  x <- gsub("AlckHosen","Alckofen",x)
  x <- gsub("Wifsenschafft","Wissenschaft",x)
  x <- gsub("wohlfenle","wohlfeine",x)
  x <- gsub("Ceniner","Centner",x)
  x <- gsub("Romaiiie","Romaine",x)
  x <- gsub("Comagnie","Compagnie",x)
  x <- gsub("Pialz","Platz",x)
  x <- gsub("Rochbuch","Kochbuch",x)
  x <- gsub("Rummer","Nummer",x)
  x <- gsub("Medieinischen", "Medicinischen",x)
  x <- gsub("Lebrling","Lehrling",x)
  x <- gsub("büte","hüte",x, ignore.case = TRUE)
  x <- gsub("Mer;","Merz",x, ignore.case = TRUE)
  x <- gsub("Hofen","Hosen",x, ignore.case = TRUE)
  x <- gsub("fust","fast",x)
  x <- gsub("fäst","fast",x)
  x <- gsub("Zeug nisse","Zeugnisse",x)
  x <- gsub("Elifabet", "Elisabet",x)
  x <- gsub("Seeretär", "Secretär", x)
  x <- gsub("Nahagoni", "Mahagoni", x)
  x <- gsub("Käsig", "Käfig", x)
  x <- gsub("Cortrait", "Portrait", x)
  x <- gsub("Beschirr", "Geschirr", x)
  x <- gsub("Korbwäelein", "Korbwägelein", x)
  x <- gsub("Mesung-Mörser", "Messing-Mörser", x)
  x <- gsub("Messtas", "Messias", x)
  x <- gsub("Srumpfii", "Stumpfii", x)
  x <- gsub("Meisibietenden", "Meistbietenden", x)
  x <- gsub("Raspar", "Kaspar", x)
  x <- gsub("Zurückgabel", "Zurückgabe", x)
  x <- gsub("Ghar-à-banc", "Char-à-banc", x)
  x <- gsub("Bögeleisen", "Bügeleisen", x)
  x <- gsub("Rothfall", "Notfall", x)
  x <- gsub("Rovität", "Novität", x)
  x <- gsub("Moskan", "Moskau", x)
  x <- gsub("Trumoau", "Trumeau", x)
  x <- gsub("BlecHosen", "Blechofen", x)
  x <- gsub("Jalousre-Läden", "Jalousie-Läden", x)
  x <- gsub("Rupfer", "Kupfer", x)
  x <- gsub("Ganeband", "Gazeband", x)
  x <- gsub("Gane-band", "Gaze-band", x)
  x <- gsub("Gane-Bänder", "Gaze-Bänder", x)
  x <- gsub("Gane-Band", "Gaze-Band", x)
  x <- gsub("Iidiennes", "Indiennes", x)
  x <- gsub("Gefinde", "Gesinde", x)
  x <- gsub("Vapolitain", "Napolitain", x)
  x <- gsub("Rode", "Mode", x)
  x <- gsub("Goldsisch", "Goldfisch", x)
  x <- gsub("Napolikames", "Napolitaines", x)
  x <- gsub("Rinder-Röck", "Kinder-Röck", x)
  x <- gsub("Rinder-Rock", "Kinder-Rock", x)
  x <- gsub("Rinderröck", "Kinderröck", x)
  x <- gsub("Rinderrock", "Kinderrock", x)
  x <- gsub("Höbe", "Höhe", x)
  x <- gsub("gleichalls", "gleichfalls", x)
  x <- gsub("Gefundheit", "Gesundheit", x)
  x <- gsub("Mareeline", "Marceline", x)
  x <- gsub("Cemnture", "Ceinture", x)
  x <- gsub("Cemture", "Ceinture", x)
  x <- gsub("Alspin", "Alépin", x)
  x <- gsub("Cor et", "Corset", x)
  x <- gsub("Uthr", "Uhr", x)
  x <- gsub("bUhr", "6Uhr", x)
  x <- gsub("Felir", "Felix", x)
  x <- gsub("Siegfrind", "Siegfried", x)
  # c and e seem to be mixed at times
  x <- gsub("ubseript","ubscript",x)
  # V and P seem to be mixed at times
  x <- gsub("Peränd","Veränd",x)
  x <- gsub("sauderm","sauberm",x)
  x <- gsub("Merckwürdigkelt","Merckwürdigkeit",x)
  x <- gsub("Ausleiben","Ausleihen",x)
  x <- gsub("Naehtrag","Nachtrag",x)
  x <- gsub("Merckwürdigkelten","Merckwürdigkeiten",x)
  x <- gsub("Kaussen","Kauffen",x)
  x <- gsub("Kaufsen","Kauffen",x)
  x <- gsub("kausen","kaufen",x)
  x <- gsub("kaufsen","kaufen",x)
  x <- gsub("Koft","Kost",x)
  x <- gsub("Verkoren","Verloren",x)
  x <- gsub("Getrante","Getraute",x)
  x <- gsub("Derloren","Verloren",x)
  x <- gsub("Perloren","Verloren",x)
  x <- gsub("Gaut","Gant",x)
  x <- gsub("Fervanf","Verkauf",x)
  x <- gsub("eidgenössiche","eidgenössische",x)
  x <- gsub("Freischiesten","Freischießen",x)
  x <- gsub("wird zu entlohnen begehrt","wird zu entlehnen begehrt",x)
  x <- gsub("Nachrichteu","Nachrichten",x)
  x <- gsub("\\befundenes","Gefundenes",x)
  x <- gsub("Gaenten","Ganten",x)
  x <- gsub("entiehnen","entlehnen",x)
  x <- gsub("Rachtrag","Nachtrag",x)
  x <- gsub("Raehtrag","Nachtrag",x)
  x <- gsub("Veerkauf","Verkauf",x)
  x <- gsub("Verkäuf\\b","Verkauf\\b",x)
  x <- gsub("Verlvrenes","Verlorenes",x)
  x <- gsub("Vierkauf","Verkauf",x)
  x <- gsub("Vorvanf","Verkauf",x)
  x <- gsub("Getrante","Getraute",x)
  x <- gsub("A(l|L|1)(l|L|1)e","Alle",x)
  x <- gsub("fremhd","frembd",x)
  x <- gsub("Nachträg\\b","Nachtrag",x)
  x <- gsub("kosament","Losament",x)
  x <- gsub("Seribenten","Scribenten",x)
  x <- gsub("Scbeuchaeridas","Scheuchaeridas",x)
  x <- gsub("Sebeuchaeri","Scheuchaeri",x)
  x <- gsub("Helverica","Helvetica",x)
  x
  }
