correct_ocr <- function(x){
  x <- gsub("Lebrling","Lehrling",x)
  x <- gsub("büte","hüte",x, ignore.case = TRUE)
  x <- gsub("Mer;","Merz",x, ignore.case = TRUE)
  x <- gsub("Hofen","Hosen",x, ignore.case = TRUE)
  x <- gsub("fust","fast",x)
  x <- gsub("fäst","fast",x)
  x <- gsub("Zeug nisse","Zeugnisse",x)
  x <- gsub("Elifabet", "Elisabet",x)
  x <- gsub("Seeretär", "Secretär", x)
  x <- gsub("Nahagoni", "Mahagoni", x)
  x <- gsub("Käsig", "Käfig", x)
  x <- gsub("Cortrait", "Portrait", x)
  x <- gsub("Beschirr", "Geschirr", x)
  x <- gsub("Korbwäelein", "Korbwägelein", x)
  x <- gsub("Mesung-Mörser", "Messing-Mörser", x)
  x <- gsub("Raspar", "Kaspar", x)
  x <- gsub("Zurückgabel", "Zurückgabe", x)
  x <- gsub("Ghar-à-banc", "Char-à-banc", x)
  x <- gsub("Bögeleisen", "Bügeleisen", x)
  x <- gsub("Rothfall", "Notfall", x)
  x <- gsub("Rovität", "Novität", x)
  x <- gsub("Moskan", "Moskau", x)
  x <- gsub("Trumoau", "Trumeau", x)
  x <- gsub("BlecHosen", "Blechofen", x)
  x <- gsub("Jalousre-Läden", "Jalousie-Läden", x)
  x <- gsub("Rupfer", "Kupfer", x)
  x <- gsub("Ganeband", "Gazeband", x)
  x <- gsub("Gane-band", "Gaze-band", x)
  x <- gsub("Gane-Band", "Gaze-Band", x)
  x <- gsub("Iidiennes", "Indiennes", x)
  x <- gsub("Gefinde", "Gesinde", x)
  x <- gsub("Vapolitain", "Napolitain", x)
  x <- gsub("Rode", "Mode", x)
  x <- gsub("Goldsisch", "Goldfisch", x)
  x <- gsub("Napolikames", "Napolitaines", x)
  x <- gsub("Rinder-Röck", "Kinder-Röck", x)
  x <- gsub("Rinder-Rock", "Kinder-Rock", x)
  x <- gsub("Rinderröck", "Kinderröck", x)
  x <- gsub("Rinderrock", "Kinderrock", x)
  x <- gsub("Höbe", "Höhe", x)
  x <- gsub("gleichalls", "gleichfalls", x)
  x
  }
