#' Provide list of umbrella terms
#' @export
umbrella_terms <- function(){
  umbrella_stand <- list(
    ut_consumables_drink = "alcohol|chocolate|coffee|milk|mineralwater|tea|syrup",
    ut_consumables_food = "butter|cheese|driedfruit|eggs|broth|fish|fruit|grain|honey|legumes|meat|mushrooms|nuts|\\boil|pasta|pastry|poultry|preserves|spices|sugar|tropicalfruit|vegetable", #\\boil otherwise will include tagfilter soil
    ut_consumables_drugs = "health|tobaccoproducts|mineralwater",
    ut_consumables_other = "firework",
    ut_household = "bed|bedding|carpet|tablelinen|cabinet|chair|stove|mirror|table|timepiece|bureau|tableware|toy|game|kitchen|lighting|instrument|wallpaper|cutlery|divider|petobject|upholstery|domestic|garden|homedeco|bathobject|art|antique|mischousehold",
    ut_clothing = "clothing|costume|uniform|outerwear|sleepwear|underwear|\\bhand|shoes|headdress|neck",
    ut_textiles = "bedding|carpet|clothing|costume|uniform|outerwear|sleepwear|underwear|\\bhand|handkerchief|shoes|headdress|neck|texmaterial|cloth|yarn",
    ut_things_accessories = "bag|mercery|jewellery|glasses|key|cane|umbrella|weapon|riding|tobaccoobjects",
    ut_things_storeNmove = "carriage|pushchair|suitcase|trolley|storage|container|barrel",
    ut_things_devicesNcomponents = "buildingcomponents|woodobjekt|shopequip|tavernobject|rope|well|agriculturalobjects|measure|stationary|tool|firestart|extinguisher|wineobject|miscobject",
    ut_things_materials = "animalraw|plantraw|plant|naturalia|wood|feed|hay|dung|soil",
    ut_animals = "dogs|birds|cats|otherpets|livestock" #what to do with animalobjects ?
  )
  umbrella_stand
}

umbrella_terms2 <- function(){
  umbrella_stand <- list(
    ut2_accessories = "\\bhand|handkerchief|bag|mercery|jewellery|glasses|cane|umbrella|tobaccoobjects",
    ut2_clothing = "clothing|costume|headdress|neck|outerwear|shows|underwear|uniform",
    #ut2_food = "butter|cheese|driedfruit|eggs|broth|fish|fruit|grain|honey|legumes|meat|mushrooms|nuts|\\boil|pasta|pastry|poultry|preserves|spices|sugar|tropicalfruit|vegetable", #\\boil otherwise will include tagfilter soil
    #ut2_drink = "alcohol|chocolate|coffee|milk|mineralwater|tea|syrup",
    #ut2_drugs = "tobaccoproducts|mineralwater",
    ut2_consumables = "butter|cheese|driedfruit|eggs|broth|fish|fruit|grain|honey|legumes|meat|mushrooms|nuts|\\boil|pasta|pastry|poultry|preserves|spices|sugar|tropicalfruit|vegetable|alcohol|chocolate|coffee|milk|mineralwater|tea|syrup|tobaccoproducts",
    ut2_household_goods = "bathobject|cutlery|domestic|game|homedeco|kitchen|lighting|mirror|mischousehold|tableware|container|storage",
    ut2_household_furniture = "bed|bureau|cabinet|chair|divider|stove|table|timepiece|upholstery|wallpaper",
    ut2_household_textiles = "bedding|carpet|tablelinen",
    ut2_materials_textile = "cloth\\b|texmaterial|yarn",
    ut2_materials_agricultural = "plant|naturalia|feed|hay|dung|soil",
    ut2_materials_industrial = "animalraw|plantraw|wood|buildingcomponents",
    ut2_animals = "dogs|birds|cats|otherpets|livestock",
    ut2_other_objects = "art|antique|garden|petobject|instrument|toy|carriage|pushchair|suitcase|trolley|container|barrel|key|weapon|riding|woodobjekt|shopequip|tavernobject|rope|well|agriculturalobjects|measure|stationary|tool|firestart|extinguisher|wineobject|miscobject"
  )
  umbrella_stand
}


#' Some tagfilters were build to be case sensitive, some were not. This gives the ones that are not sensitive
#' @export
tf_ignorecase <- function(prefix = F){
  l <- c("agriculturalobjects",
         "alcohol",
         "animalobjects",
         "animalraw",
         "antique",
         "art",
         "bag",
         "barrel",
         "bathobject",
         "bed",
         "bedding",
         "broth",
         "buildingcomponents",
         "bureau",
         "butter",
         "cabinet",
         "cane",
         "carpet",
         "carriage",
         "chair",
         "cheese",
         "chocolate",
         "cloth",
         "clothing",
         "coffee",
         "container",
         "cooking",
         "costume",
         "crime",
         "cutlery",
         "divider",
         "domestic",
         "driedfruit",
         "dung",
         "eggs",
         "extinguisher",
         "feed",
         "firestart",
         "firework",
         "fish",
         "fruit",
         "game",
         "garden",
         "glasses",
         "grain",
         "hand",
         "handkerchief",
         "hay",
         "headdress",
         "health",
         "homedeco",
         "honey",
         "instrument",
         "jewellery",
         "key",
         "kitchen",
         "knitting",
         "legumes",
         "lighting",
         "livestock",
         "measure",
         "meat",
         "mercery",
         "milk",
         "mineralwater",
         "mirror",
         "mischousehold",
         "miscobject",
         "mushrooms",
         "naturalia",
         "neck",
         "nuts",
         "oil",
         "outerwear",
         "pasta",
         "pastry",
         "petobject",
         "plant",
         "plantraw",
         "poultry",
         "preserves",
         "pushchair",
         "riding",
         "rope",
         "secondhand",
         "shoes",
         "shopequip",
         "sleepwear",
         "soil",
         "spices",
         "spinning",
         "stationary",
         "storage",
         "stove",
         "sugar",
         "suitcase",
         "syrup",
         "table",
         "tablelinen",
         "tableware",
         "tavernobject",
         "texmaterial",
         "timepiece",
         "tobaccoobjects",
         "tobaccoproducts",
         "tool",
         "toy",
         "trolley",
         "tropicalfruit",
         "umbrella",
         "underwear",
         "uniform",
         "upholstery",
         "vegetable",
         "wallpaper",
         "weapon",
         "weaving",
         "well",
         "wineobject",
         "wood",
         "woodobject",
         "yarn"
  )
  if (prefix) {paste0("tagfilter_", l)}
  else {l}
}